---
- name: Installing and configuring Nginx on servers
  hosts: webservers
  become: true

  tasks:
  - name: Installing Nginx
    apt:
      name: nginx 
      state: present
  - name: Start Nginx
    service:
      name: nginx
      state: started
      enabled: yes

